In [ ]:
a=int(input("Enter you marks: "))
if a>=50:
    print("Merit")
elif(a>=30 and a<50):
    print("Pass")
elif(a<30):
    print("Fail")

In [ ]:
fruits=["apple","banana","orange"]
for i in range(0,11):
    print(i+1)

1
2
3
4
5
6
7
8
9
10
11


In [3]:
i=0
while i<10:
    print("Condition ",i)
    i=i+1

Condition  0
Condition  1
Condition  2
Condition  3
Condition  4
Condition  5
Condition  6
Condition  7
Condition  8
Condition  9


### DAY 2

In [1]:
a=int(input("Enter first number "))
b=int(input("Enter second number "))
for i in range(a,b+1):
    if(i%5==0 and i%7==0):
        print(i,end=" ")

35 

In [9]:
a=int(input("Enter a number: "))
b=int(input("Enter a number: "))
c=int(input("Enter a number: "))
if(a>b and a>c):
    print("Greater number is ",a)
elif(b>a and b>c):
    print("Greater number is ",b)
elif(c>a and c>b):
    print("Greater number is ",c)

Greater number is  3


In [14]:
for i in range(1,6):
    for j in range(1,i+1):
        print(j,end=" ")
    print(end="\n")

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [19]:
for letter in 'python':
    if letter =='o':
        break
    print(letter)

p
y
t
h


In [20]:
for letter in 'python':
    if letter =='o':
       continue
    print(letter)

p
y
t
h
n


In [21]:
s="hello world concatenate me!"
s[0:10]

'hello worl'

In [22]:
s.split(" ")

['hello', 'world', 'concatenate', 'me!']

In [23]:
s.split("w")

['hello ', 'orld concatenate me!']

In [24]:
print("Hey {} {} {} {}".format("Krishna","are","you","enjoying"))

Hey Krishna are you enjoying


In [25]:
name="Krishna"
print(f"Hello {name} , it's time to stop!")

Hello Krishna , it's time to stop!


In [26]:
print("I am going to inject %s here %f "%("'something'",6.2))

I am going to inject 'something' here 6.200000 


In [36]:
mylist=[1,2,3,4,5,'alpha','beta']
print(mylist)

[1, 2, 3, 4, 5, 'alpha', 'beta']


In [37]:
mylist +['Krishna']

[1, 2, 3, 4, 5, 'alpha', 'beta', 'Krishna']

In [38]:
print(mylist)

[1, 2, 3, 4, 5, 'alpha', 'beta']


In [39]:
mylist=mylist +['Krishna']
print(mylist)

[1, 2, 3, 4, 5, 'alpha', 'beta', 'Krishna']


In [ ]:
fhand=open(".txt")
type(fhand)
try:
    fhand=open("lucifer.txt")
    for line in fhand:
        line=line.rstrip()
        if line.startswith("From: "):
            print(line)
except:
    print("File not found")

In [1]:

def add_numbers(x,y):
    total_sum=x+y
    return total_sum

num1=5
num2=6
x=0
y=0
x,y=add_numbers(num1,num2)
print("The sum is ",x," ",y)

TypeError: cannot unpack non-iterable int object

In [2]:

def add_numbers(x,y):
    total_sum=x+y
    return total_sum,5

num1=5
num2=6
x=0
y=0
x=add_numbers(num1,num2)
print("The sum is ",x," ",y)

The sum is  (11, 5)   0


In [3]:
def starts_with_A(s):
    return s[0]=="A"

fruit=["Apple","Banana","Peer","Apricot","Orange"]
filter_object=filter(starts_with_A,fruit)
print(list(filter_object))

['Apple', 'Apricot']


In [4]:
l=list(map(int,input().split()))
print("Map List: ",l)

Map List:  [4, 5, 6, 7, 8]


In [5]:
from functools import reduce
num_list=[0,1,2,1,2,3,5,8,13,21,34,55]
print("Length of num_list ",len(num_list))
s=reduce(lambda a,b:a+b,num_list)
print("Sum= ",s)

Length of num_list  12
Sum=  145


In [6]:
def fact(n):
    if n<0:
        return 0
    elif n==0 or n==1:
        return 1
    else:
        fac=1
        while n>1:
            fac=fac*n
            n=n-1
        return fac

num=5
print("Factorial is: ",fact(num))

#using reduce and lambda
from functools import reduce
print("Factorial = ",reduce(lambda a,b:a*b,range(1,num+1)))

Factorial is:  120
Factorial=  120


In [7]:
list1=[15,17,18,9]
print(max(list1))

18


In [8]:
list1=['15','17','18','9']
print(max(list1))

9


In [9]:
any([5>8,6<3,3>1])

True

In [10]:
x="ABC"
print(type(x))
print(dir(x))

<class 'str'>
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


## NUmpy()

In [11]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
print(np.__version__)

1.19.5


In [13]:
x=12j
print(type(x))
type(arr)
arr.ndim

<class 'complex'>


1

In [14]:
my_arr=np.arange(1000000)
print(my_arr)

[     0      1      2 ... 999997 999998 999999]


In [ ]:
my_list=list(range(1000000))
print(my_list)

In [29]:
import numpy as np
a=np.array(42)
e=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4,5]])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(e.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
2
3


In [30]:
print(np.linspace(1,10))
print(np.linspace(10,20,5))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[10.  12.5 15.  17.5 20. ]


In [31]:
A=np.array([
    [11,12,13,14,51],
    [21,22,23,24,25],
    [31,32,33,34,45],
    [41,42,43,44,45]
])
print(A[:3,2:])

[[13 14 51]
 [23 24 25]
 [33 34 45]]


In [32]:
X=np.arange(28).reshape(4,7)
print(X)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [34]:
W=np.ones((2,3))
print(W)

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
Z=np.zeros((2,4))
print(Z)
V=np.empty((2,4))
print(V)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
Y=Z
Y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
Z[1,1]=3
Z

array([[0., 0., 0., 0.],
       [0., 3., 0., 0.]])

In [39]:
Y

array([[0., 0., 0., 0.],
       [0., 3., 0., 0.]])

In [40]:
x=np.array([[42,22,12],[44,53,66]],order='F')
y=x.copy()
x[0,0]=100
print(x)
print(y)

[[100  22  12]
 [ 44  53  66]]
[[42 22 12]
 [44 53 66]]


In [41]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [42]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [43]:
np.tile([1,2,3],3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
mylist=[1,2,3]
x=np.array(mylist)
x
y=np.array([4,5,6])
y

array([4, 5, 6])

In [45]:
print(x+y)

[5 7 9]


In [46]:
print(x-y)

[-3 -3 -3]


In [49]:
print(x*y)
x.dot(y)

[ 4 10 18]


32

In [50]:
a=np.array([-4,-2,1,3,5,7,9,11,-4,1,4,1])
print(a.sum())
print(a.max())
print(a.argmax())
print(a.min())
print(a.argmin())
print(a.mean())
print(a.var())
print(a.std())

32
11
7
-4
0
2.6666666666666665
21.222222222222218
4.606758320361751


In [51]:
# Write a NumPy program to compute the determinant of a given square array.
import numpy as np
from numpy import linalg 
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
np.linalg.det(a)

Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:


2.0

In [52]:
#from numpy import random
#x=random.logistic

In [54]:
import pandas as pd

In [55]:
pd.DataFrame({'Yes':[50,21],'No':[131,2]})

Yes   No
0   50  131
1   21    2

In [56]:
pd.DataFrame({'Bob':['I liked it.','It was awful'],'Sue':['Pretty good.','Bland.']})

Bob           Sue
0   I liked it.  Pretty good.
1  It was awful        Bland.

In [57]:
pd.DataFrame({'Bob':['I liked it.','It was awful'],'Sue':['Pretty good.','Bland.']},index=['Product A','Product B'])

Bob           Sue
Product A   I liked it.  Pretty good.
Product B  It was awful        Bland.

In [58]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [61]:
pd.Series([1,2,3,4,5],index=['2015 sales','2016 sales','2017 sales','2018 sales','2019 sales'])

2015 sales    1
2016 sales    2
2017 sales    3
2018 sales    4
2019 sales    5
dtype: int64

In [1]:
s=[{()}]
print(type(s))

<class 'list'>


How can we find the type of numpy array in python?

==> dtype

Each location of an element in an array is called ?
==>index

In [3]:
dict1={"key1":1,"key2":2}
dict2={"key2":2,"key1":1}
print(dict1==dict2)

True


In [5]:
x=36/4*(3+2)*4+2
print(x)

182.0


In [12]:
x=0
a=0
b=-5
if a>0:
    if b<0:
        x=x+5
    elif a>5:
        x=x+4
    else:
        x=x+3
else:
    x=x+2
print(x)

2


In [7]:
(lambda x:x*2)(12)

24

In [8]:
a,a=2,3
print(a)

3


In [9]:
type(4)==type(4.5//2)

False

In [10]:
x="ILovePython"
stuff={i for i in x}
print(len(stuff))

10


In [13]:
s={}
print(type(s))

<class 'dict'>


In [15]:
a=10
b=3
print(a%b,a//b)

1 3


who is the main author of pandas
==>Wes McKinney

In [16]:
a,a=2,3
print(a)

3


In [18]:
a=True+False
r=True or False
print(a+r)

2


In [20]:
a=3--2--1
print(a)

6


In [22]:
list1=['xyz','zara','PYnative']
print(max(list1))

zara


In [23]:
s="PythonCoder"
a=s.isalpha()
print(a)

True


In [24]:
a="Coding"
b=a[2:6:1]
b

'ding'

In [25]:
a=[4,4,3,5,7]
list(set(a))
a[1]

4

In [26]:
def myfunc(a):
    a=a+2
    a=a*a
    return a
print(myfunc(2))

16


In [27]:
tuple=(1,2,3)
new_tuple=tuple,4,5
print(new_tuple)

((1, 2, 3), 4, 5)


In [28]:
max('1','A')

'A'

In [29]:
ord('B')


66

In [30]:
ord('ABC')

TypeError: ord() expected a character, but string of length 3 found

In [1]:
str="Hello"
print(str[::-1])

olleH


In [3]:
def hotel_cost(nights):
    return nights*140

def plane_ride_cost(city):
    if city=="Charlotte":
        return 183
    elif city=="Tampa":
        return 220
    elif city=="Pittsburgh":
        return 222
    elif city=="Los Angeles":
        return 475
    
def rental_car_cost(days):
    return days*40

def trip_cost(nights,city,rental):
    total = hotel_cost(nights) + rental_car_cost(days) + plane_ride_cost(city)
    if rental>=7:
        total -= 50
    elif rental>=3:
        total -= 20
    return total

nights = int(input('Enter Night:'))
city = input('Enter City:')
rental = int(input('Enter rental car days:'))
spending = int(input('Enter spending: '))

res = trip_cost(nights,city,rental)
print('Total cost:', res+spending)

NameError: name 'days' is not defined

In [1]:
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)


apple
banana
cherry


In [2]:
x = "Python is "
y = "awesome"
z = x + y
print(z)

Python is awesome


In [3]:
x = 5
y = "John"
print(x + y)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [4]:
x = 5
y = 10
print(x + y)

15


In [6]:
x = "awesome"
def myfunc():
    x = "fantastic"
    print("Python is " + x)
myfunc()
print("Python is " + x)


Python is fantastic
Python is awesome


In [7]:
for x in "banana":
 print(x)

b
a
n
a
n
a


In [8]:
b = "Hello, World!"
print(b[2:5])

llo


In [1]:
fruits = ("apple", "banana", "cherry")
(green, yellow, red) = fruits
print(green)
print(yellow)
print(red)

apple
banana
cherry


In [2]:
fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")
(green, yellow, *red) = fruits
print(green)
print(yellow)
print(red)

apple
banana
['cherry', 'strawberry', 'raspberry']


In [3]:
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")
(green, *tropic, red) = fruits
print(green)
print(tropic)
print(red)

apple
['mango', 'papaya', 'pineapple']
cherry


In [4]:
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
 print(x)


apple
banana
cherry


In [5]:
thisset = {"apple", "banana", "cherry"}
print(thisset)


{'apple', 'banana', 'cherry'}


In [7]:
thisset = {"apple", "banana", "cherry"}
thisset.add("orange")
print(thisset)

{'orange', 'apple', 'banana', 'cherry'}


In [9]:
thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}
thisset.update(tropical)
print(thisset)

{'papaya', 'apple', 'mango', 'pineapple', 'banana', 'cherry'}


In [10]:
thisset = {"apple", "banana", "cherry"}
thisset.remove("banana")
print(thisset)


{'apple', 'cherry'}


In [11]:
thisdict = {
 "brand": "Ford",
 "model": "Mustang",
 "year": 1964
}
thisdict.update({"year": 2020})


In [12]:
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}


In [1]:
for x in range(2, 30, 3):
 print(x)


2
5
8
11
14
17
20
23
26
29


In [2]:
for x in range(6):
 if x == 3: break
 print(x)
else:
 print("Finally finished!")


0
1
2


In [3]:
x = 300
def myfunc():
   x = 200
   print(x)
myfunc()
print(x)


200
300


In [4]:
age = 36
name = "John"
txt = "His name is {1}. {1} is {0} years old."
print(txt.format(age, name))


His name is John. John is 36 years old.
